In [11]:
from utils import get_gsm8k
import pandas as pd
import numpy as np

df = get_gsm8k()
df.head()

GSM8K
gemma-3-27b-it.xlsx
qwen3_1.7b.xlsx
smollm2_360m.xlsx
qwen2-math_1.5b.xlsx
qwen3_0.6b.xlsx
qwen2.5_0.5b.xlsx
gemma3_1b.xlsx
deepseek-r1_1.5b.xlsx
llama3.2_1b.xlsx
DP-Reflection
qwen3_1.7b.xlsx
qwen3_0.6b.xlsx
qwen2.5_0.5b.xlsx
deepseek-r1_1.5b.xlsx
ReAct
qwen3_1.7b.xlsx
qwen3_0.6b.xlsx
qwen2.5_0.5b.xlsx
llama3.2_1b.xlsx
ReWOO
gemma-3-27b-it.xlsx
qwen3_1.7b.xlsx
smollm2_360m.xlsx
qwen2-math_1.5b.xlsx
qwen3_0.6b.xlsx
qwen2.5_0.5b.xlsx
gemma3_1b.xlsx
deepseek-r1_1.5b.xlsx
llama3.2_1b.xlsx

,Dataset,Method,Model,question,target_answer,response,is_correct,input_tokens,output_tokens,total_tokens,reasoning,Error Class,Error Type
0,GSM8K,Direktes Prompting,gemma-3-27b-it,Janet‚Äôs ducks lay 16 eggs per day. She eats ...,Janet sells 16 - 3 - 4 = <<16-3-4=9>>9 duck eg...,Let $E$ be the number of eggs Janet's ducks la...,True,NaN,NaN,NaN,Let $E$ be the number of eggs Janet's ducks la...,NaN,NaN
1,GSM8K,Direktes Prompting,gemma-3-27b-it,A robe takes 2 bolts of blue fiber and half th...,It takes 2/2=<<2/2=1>>1 bolt of white fiber\nS...,Let the number of bolts of blue fiber be $B$ a...,True,NaN,NaN,NaN,Let the number of bolts of blue fiber be $B$ a...,NaN,NaN
2,GSM8K,Direktes Prompting,gemma-3-27b-it,Josh decides to try flipping a house. He buys...,The cost of the house and repairs came out to ...,Let the initial cost of the house be $C = \$80...,True,NaN,NaN,NaN,Let the initial cost of the house be $C = \$80...,NaN,NaN
3,GSM8K,Direktes Prompting,gemma-3-27b-it,James decides to run 3 sprints 3 times a week....,He sprints 3*3=<<3*3=9>>9 times\nSo he runs 9*...,Let $s$ be the number of sprints James runs ea...,True,NaN,NaN,NaN,Let $s$ be the number of sprints James runs ea...,NaN,NaN
4,GSM8K,Direktes Prompting,gemma-3-27b-it,"Every day, Wendi feeds each of her chickens th...","If each chicken eats 3 cups of feed per day, t...",Let $n$ be the number of chickens Wendi has. W...,True,NaN,NaN,NaN,Let $n$ be the number of chickens Wendi has. W...,NaN,NaN

In [6]:
df_misc = get_gsm8k(include_misclassified=True)
df_misc = df_misc[df_misc["Error Type"] == "Misclassified"]

GSM8K
gemma-3-27b-it.xlsx
qwen3_1.7b.xlsx
smollm2_360m.xlsx
qwen2-math_1.5b.xlsx
qwen3_0.6b.xlsx
qwen2.5_0.5b.xlsx
gemma3_1b.xlsx
deepseek-r1_1.5b.xlsx
llama3.2_1b.xlsx
DP-Reflection
qwen3_1.7b.xlsx
qwen3_0.6b.xlsx
qwen2.5_0.5b.xlsx
deepseek-r1_1.5b.xlsx
ReAct
qwen3_1.7b.xlsx
qwen3_0.6b.xlsx
qwen2.5_0.5b.xlsx
llama3.2_1b.xlsx
ReWOO
gemma-3-27b-it.xlsx
qwen3_1.7b.xlsx
smollm2_360m.xlsx
qwen2-math_1.5b.xlsx
qwen3_0.6b.xlsx
qwen2.5_0.5b.xlsx
gemma3_1b.xlsx
deepseek-r1_1.5b.xlsx
llama3.2_1b.xlsx

In [7]:
overall_misc_rate = len(df_misc) / len(df)
print(f"Total misclassified examples: {len(df_misc)}")
print(f"Total examples: {len(df)}")
print(f"Overall misclassification rate: {overall_misc_rate:.2%}")

Total misclassified examples: 62
Total examples: 7800
Overall misclassification rate: 0.79%

In [8]:
df_misc.groupby(["Model", "Method", "Error Class"]).agg({
    "question": "count",
}).reset_index().pivot_table(index=["Model"], columns="Method", values="question", fill_value=pd.NA)

Method            Direktes Prompting  ReAct  ReWOO
Model
deepseek-r1:1.5b                16.0    NaN    5.0
gemma-3-27b-it                   3.0    NaN    1.0
gemma3:1b                        NaN    NaN    2.0
llama3.2:1b                      5.0    1.0    NaN
qwen2-math:1.5b                  8.0    NaN    NaN
qwen2.5:0.5b                     6.0    1.0    2.0
qwen3:0.6b                       NaN    5.0    NaN
qwen3:1.7b                       3.0    2.0    NaN
smollm2:360m                     2.0    NaN    NaN

# TO

In [12]:
df_acc = df.groupby(["Method", "Model"]).agg({
    "is_correct": "mean",
}).reset_index()

df_acc["is_correct"] = round(df_acc["is_correct"] * 100, 2)  # Convert to percentage
# pivot to have Method as Columns
df_acc = df_acc.pivot_table(index=["Model"], columns="Method", values="is_correct", fill_value=np.nan).reset_index()
df_acc.head(50)

Method             Model  DP-Reflection  Direktes Prompting  ReAct  ReWOO
0       deepseek-r1:1.5b          66.00               73.33    NaN  77.33
1         gemma-3-27b-it            NaN               97.33    NaN  89.00
2              gemma3:1b            NaN               58.67    NaN  11.33
3            llama3.2:1b            NaN               50.67  24.00   4.00
4        qwen2-math:1.5b            NaN               82.33    NaN   0.33
5           qwen2.5:0.5b          35.00               40.33  15.67  12.33
6             qwen3:0.6b          68.67               61.00  64.67  55.33
7             qwen3:1.7b          87.33               66.67  85.33  74.33
8           smollm2:360m            NaN                5.33    NaN   2.33

In [13]:
from statistical_significance import compare_accuracies_v3

In [8]:
df_t = (
    df.groupby(["Method", "Model"])
    .agg({
        "is_correct": ["sum", "mean"]
    })
    .reset_index()
    .sort_values(by=("is_correct", "sum"), ascending=False)
    .reset_index(drop=True)
)
df_t

                Method             Model is_correct
                                                sum      mean
0   Direktes Prompting    gemma-3-27b-it        292  0.973333
1                ReWOO    gemma-3-27b-it        267  0.890000
2                ReAct        qwen3:1.7b        256  0.853333
3   Direktes Prompting   qwen2-math:1.5b        247  0.823333
4                ReWOO  deepseek-r1:1.5b        232  0.773333
5                ReWOO        qwen3:1.7b        223  0.743333
6   Direktes Prompting  deepseek-r1:1.5b        220  0.733333
7   Direktes Prompting        qwen3:1.7b        200  0.666667
8                ReAct        qwen3:0.6b        194  0.646667
9   Direktes Prompting        qwen3:0.6b        183  0.610000
10  Direktes Prompting         gemma3:1b        176  0.586667
11               ReWOO        qwen3:0.6b        166  0.553333
12  Direktes Prompting       llama3.2:1b        152  0.506667
13  Direktes Prompting      qwen2.5:0.5b        121  0.403333
14               ReAct       llama3.2:1b         72  0.240000
15               ReAct      qwen2.5:0.5b         47  0.156667
16               ReWOO      qwen2.5:0.5b         37  0.123333
17               ReWOO         gemma3:1b         34  0.113333
18  Direktes Prompting      smollm2:360m         16  0.053333
19               ReWOO       llama3.2:1b         12  0.040000
20               ReWOO      smollm2:360m          7  0.023333
21               ReWOO   qwen2-math:1.5b          1  0.003333

In [4]:
mean_token_usage = df.groupby(["Model", "Method"]).agg(
    mean_correct_answers=("is_correct", "mean"),
    mean_input_tokens=("input_tokens", "mean"),
    mean_output_tokens=("output_tokens", "mean"),
    mean_total_tokens=("total_tokens", "mean"),
)
mean_token_usage

                                     mean_correct_answers  mean_input_tokens  \
Model            Method
deepseek-r1:1.5b DP-Reflection                   0.660000        3171.130000
                 Direktes Prompting              0.733333          63.633333
                 ReWOO                           0.773333         761.306667
gemma-3-27b-it   Direktes Prompting              0.973333                NaN
                 ReWOO                           0.890000         915.036667
gemma3:1b        Direktes Prompting              0.586667          69.140000
                 ReWOO                           0.113333         805.383333
llama3.2:1b      Direktes Prompting              0.506667          83.260000
                 ReAct                           0.240000         681.390000
                 ReWOO                           0.040000         743.496667
qwen2-math:1.5b  Direktes Prompting              0.823333          66.633333
                 ReWOO                           0.003333         532.840000
qwen2.5:0.5b     DP-Reflection                   0.350000        2215.643333
                 Direktes Prompting              0.403333          89.633333
                 ReAct                           0.156667        1072.180000
                 ReWOO                           0.123333         824.213333
qwen3:0.6b       DP-Reflection                   0.686667        4732.633333
                 Direktes Prompting              0.610000          68.633333
                 ReAct                           0.646667         547.066667
                 ReWOO                           0.553333         754.438127
qwen3:1.7b       DP-Reflection                   0.873333        5361.966667
                 Direktes Prompting              0.666667          68.633333
                 ReAct                           0.853333        1266.916667
                 ReWOO                           0.743333         796.993333
smollm2:360m     Direktes Prompting              0.053333          91.290000
                 ReWOO                           0.023333         770.476667

                                     mean_output_tokens  mean_total_tokens
Model            Method
deepseek-r1:1.5b DP-Reflection              1927.616667        5098.746667
                 Direktes Prompting          621.960000         685.593333
                 ReWOO                      1137.163333        1898.470000
gemma-3-27b-it   Direktes Prompting                 NaN                NaN
                 ReWOO                         0.000000         915.036667
gemma3:1b        Direktes Prompting          642.086667         711.226667
                 ReWOO                       231.256667        1036.640000
llama3.2:1b      Direktes Prompting          163.753333         247.013333
                 ReAct                       138.446667         819.836667
                 ReWOO                        85.740000         829.236667
qwen2-math:1.5b  Direktes Prompting          311.493333         378.126667
                 ReWOO                       312.523333         845.363333
qwen2.5:0.5b     DP-Reflection              1103.156667        3318.800000
                 Direktes Prompting          313.270000         402.903333
                 ReAct                       121.580000        1193.760000
                 ReWOO                       233.640000        1057.853333
qwen3:0.6b       DP-Reflection              3003.710000        7736.343333
                 Direktes Prompting         1393.890000        1462.523333
                 ReAct                       680.106667        1227.173333
                 ReWOO                      1405.401338        2159.839465
qwen3:1.7b       DP-Reflection              3332.160000        8694.126667
                 Direktes Prompting         1650.903333        1719.536667
                 ReAct                       865.240000        2132.156667
                 ReWOO                      1321.230000        2118.223333
smollm2:360m     Direktes Prompting          247.313333         338.603333
                 ReWOO                       353.676667        1124.153333

In [11]:
ltx = mean_token_usage.reset_index().to_latex(
    index=False,
    caption='Durchschnittliche Token-Nutzung und korrekte Antworten für GSM8K nach Modell und Methode',
    label='tab:mean_token_usage_gsm8k',
)
print(ltx)

\begin{table}
\caption{Durchschnittliche Token-Nutzung und korrekte Antworten für GSM8K nach Modell und Methode}
\label{tab:mean_token_usage_gsm8k}
\begin{tabular}{llrrrr}
\toprule
Model & Method & mean_correct_answers & mean_input_tokens & mean_output_tokens & mean_total_tokens \\
\midrule
deepseek-r1:1.5b & Direktes Prompting & 0.733333 & 63.633333 & 621.960000 & 685.593333 \\
deepseek-r1:1.5b & ReWOO & 0.773333 & 761.306667 & 1137.163333 & 1898.470000 \\
gemma-3-27b-it & Direktes Prompting & 0.973333 & NaN & NaN & NaN \\
gemma-3-27b-it & ReWOO & 0.890000 & 915.036667 & 0.000000 & 915.036667 \\
gemma3:1b & Direktes Prompting & 0.586667 & 69.140000 & 642.086667 & 711.226667 \\
gemma3:1b & ReWOO & 0.113333 & 805.383333 & 231.256667 & 1036.640000 \\
llama3.2:1b & Direktes Prompting & 0.506667 & 83.260000 & 163.753333 & 247.013333 \\
llama3.2:1b & ReAct & 0.240000 & 681.390000 & 138.446667 & 819.836667 \\
llama3.2:1b & ReWOO & 0.040000 & 743.496667 & 85.740000 & 829.236667 \\
qwen2-math:1.5b & Direktes Prompting & 0.823333 & 66.633333 & 311.493333 & 378.126667 \\
qwen2-math:1.5b & ReWOO & 0.003333 & 532.840000 & 312.523333 & 845.363333 \\
qwen2.5:0.5b & Direktes Prompting & 0.403333 & 89.633333 & 313.270000 & 402.903333 \\
qwen2.5:0.5b & ReAct & 0.156667 & 1072.180000 & 121.580000 & 1193.760000 \\
qwen2.5:0.5b & ReWOO & 0.123333 & 824.213333 & 233.640000 & 1057.853333 \\
qwen3:0.6b & Direktes Prompting & 0.610000 & 68.633333 & 1393.890000 & 1462.523333 \\
qwen3:0.6b & ReAct & 0.646667 & 547.066667 & 680.106667 & 1227.173333 \\
qwen3:0.6b & ReWOO & 0.553333 & 754.438127 & 1405.401338 & 2159.839465 \\
qwen3:1.7b & Direktes Prompting & 0.666667 & 68.633333 & 1650.903333 & 1719.536667 \\
qwen3:1.7b & ReAct & 0.853333 & 1266.916667 & 865.240000 & 2132.156667 \\
qwen3:1.7b & ReWOO & 0.743333 & 796.993333 & 1321.230000 & 2118.223333 \\
smollm2:360m & Direktes Prompting & 0.053333 & 91.290000 & 247.313333 & 338.603333 \\
smollm2:360m & ReWOO & 0.023333 & 770.476667 & 353.676667 & 1124.153333 \\
\bottomrule
\end{tabular}
\end{table}

In [3]:
df[df["is_correct"] == True].groupby(["Model", "Method"]).agg(
    mean_correct_answers=("is_correct", "mean"),
    mean_input_tokens=("input_tokens", "mean"),
    mean_output_tokens=("output_tokens", "mean"),
    mean_total_tokens=("total_tokens", "mean"),
)

                                     mean_correct_answers  mean_input_tokens  \
Model            Method
deepseek-r1:1.5b DP-Reflection                        1.0        3012.404040
                 Direktes Prompting                   1.0          59.990909
                 ReWOO                                1.0         782.146552
gemma-3-27b-it   Direktes Prompting                   1.0                NaN
                 ReWOO                                1.0         901.749064
gemma3:1b        Direktes Prompting                   1.0          62.017045
                 ReWOO                                1.0         793.911765
llama3.2:1b      Direktes Prompting                   1.0          76.355263
                 ReAct                                1.0         660.347222
                 ReWOO                                1.0         730.416667
qwen2-math:1.5b  Direktes Prompting                   1.0          64.246964
                 ReWOO                                1.0         642.000000
qwen2.5:0.5b     DP-Reflection                        1.0        2020.580952
                 Direktes Prompting                   1.0          80.049587
                 ReAct                                1.0         948.702128
                 ReWOO                                1.0         804.189189
qwen3:0.6b       DP-Reflection                        1.0        4254.776699
                 Direktes Prompting                   1.0          61.262295
                 ReAct                                1.0         503.561856
                 ReWOO                                1.0         785.909091
qwen3:1.7b       DP-Reflection                        1.0        5216.030534
                 Direktes Prompting                   1.0          65.340000
                 ReAct                                1.0        1271.714844
                 ReWOO                                1.0         806.417040
smollm2:360m     Direktes Prompting                   1.0          81.312500
                 ReWOO                                1.0         882.285714

                                     mean_output_tokens  mean_total_tokens
Model            Method
deepseek-r1:1.5b DP-Reflection              1764.146465        4776.550505
                 Direktes Prompting          552.936364         612.927273
                 ReWOO                      1023.405172        1805.551724
gemma-3-27b-it   Direktes Prompting                 NaN                NaN
                 ReWOO                         0.000000         901.749064
gemma3:1b        Direktes Prompting          378.579545         440.596591
                 ReWOO                       268.411765        1062.323529
llama3.2:1b      Direktes Prompting          127.282895         203.638158
                 ReAct                       115.347222         775.694444
                 ReWOO                        66.250000         796.666667
qwen2-math:1.5b  Direktes Prompting          291.004049         355.251012
                 ReWOO                       381.000000        1023.000000
qwen2.5:0.5b     DP-Reflection               957.190476        2977.771429
                 Direktes Prompting          259.801653         339.851240
                 ReAct                       124.893617        1073.595745
                 ReWOO                       291.972973        1096.162162
qwen3:0.6b       DP-Reflection              2577.970874        6832.747573
                 Direktes Prompting         1101.540984        1162.803279
                 ReAct                       508.041237        1011.603093
                 ReWOO                      1068.290909        1854.200000
qwen3:1.7b       DP-Reflection              3129.698473        8345.729008
                 Direktes Prompting         1452.380000        1517.720000
                 ReAct                       753.750000        2025.464844
                 ReWOO                      1059.251121        1865.668161
smollm2:360m     Direktes Prompting          152.312500         233.625000
                 ReWOO                       189.000000        1071.285714

In [ ]:
df[df["is_correct"] == False].groupby(["Model", "Method"]).agg(
    mean_correct_answers=("is_correct", "mean"),
    mean_input_tokens=("input_tokens", "mean"),
    mean_output_tokens=("output_tokens", "mean"),
    mean_total_tokens=("total_tokens", "mean"),
)

In [ ]:
df[df["Error Class"] == "Too Few Tokens"].groupby(["Method", "Model"]).agg({
    "Error Class": "count",
    "is_correct": "mean"
})

## Signifikanztest

In [24]:
import pandas as pd
n = 300
significant_results = []
for idx, row in df_acc.iterrows():
    methods = df["Method"].unique()
    for i in range(len(methods)):
        for j in range(i + 1, len(methods)):
            method1 = methods[i]
            method2 = methods[j]
            score1 = row[method1]
            score2 = row[method2]
            result = compare_accuracies_v3(score1/100, n, score2/100, n)
            significant_results.append((row["Model"], row["Model"], method1, method2, score1, score2, result.p_value, result.is_significant))

significant_results_df = pd.DataFrame([
    {
        'Model': model1,
        # 'Model2': model2,
        'Method1': method1,
        'Method2': method2,
        'Score1': score1,
        'Score2': score2,
        'p_value': p_value,
        'is_significant': is_significant
    }
    for model1, model2, method1, method2, score1, score2, p_value, is_significant in significant_results
])
print(significant_results_df.to_latex(index=False))

\begin{tabular}{lllrrrr}
\toprule
Model & Method1 & Method2 & Score1 & Score2 & p_value & is_significant \\
\midrule
deepseek-r1:1.5b & Direktes Prompting & DP-Reflection & 73.330000 & 66.000000 & 0.050102 & False \\
deepseek-r1:1.5b & Direktes Prompting & ReAct & 73.330000 & NaN & 1.000000 & False \\
deepseek-r1:1.5b & Direktes Prompting & ReWOO & 73.330000 & 77.330000 & 0.255271 & False \\
deepseek-r1:1.5b & DP-Reflection & ReAct & 66.000000 & NaN & 1.000000 & False \\
deepseek-r1:1.5b & DP-Reflection & ReWOO & 66.000000 & 77.330000 & 0.001909 & True \\
deepseek-r1:1.5b & ReAct & ReWOO & NaN & 77.330000 & 1.000000 & False \\
gemma-3-27b-it & Direktes Prompting & DP-Reflection & 97.330000 & NaN & 1.000000 & False \\
gemma-3-27b-it & Direktes Prompting & ReAct & 97.330000 & NaN & 1.000000 & False \\
gemma-3-27b-it & Direktes Prompting & ReWOO & 97.330000 & 89.000000 & 0.000041 & True \\
gemma-3-27b-it & DP-Reflection & ReAct & NaN & NaN & 1.000000 & False \\
gemma-3-27b-it & DP-Reflection & ReWOO & NaN & 89.000000 & 1.000000 & False \\
gemma-3-27b-it & ReAct & ReWOO & NaN & 89.000000 & 1.000000 & False \\
gemma3:1b & Direktes Prompting & DP-Reflection & 58.670000 & NaN & 1.000000 & False \\
gemma3:1b & Direktes Prompting & ReAct & 58.670000 & NaN & 1.000000 & False \\
gemma3:1b & Direktes Prompting & ReWOO & 58.670000 & 11.330000 & 0.000000 & True \\
gemma3:1b & DP-Reflection & ReAct & NaN & NaN & 1.000000 & False \\
gemma3:1b & DP-Reflection & ReWOO & NaN & 11.330000 & 1.000000 & False \\
gemma3:1b & ReAct & ReWOO & NaN & 11.330000 & 1.000000 & False \\
llama3.2:1b & Direktes Prompting & DP-Reflection & 50.670000 & NaN & 1.000000 & False \\
llama3.2:1b & Direktes Prompting & ReAct & 50.670000 & 24.000000 & 0.000000 & True \\
llama3.2:1b & Direktes Prompting & ReWOO & 50.670000 & 4.000000 & 0.000000 & True \\
llama3.2:1b & DP-Reflection & ReAct & NaN & 24.000000 & 1.000000 & False \\
llama3.2:1b & DP-Reflection & ReWOO & NaN & 4.000000 & 1.000000 & False \\
llama3.2:1b & ReAct & ReWOO & 24.000000 & 4.000000 & 0.000000 & True \\
qwen2-math:1.5b & Direktes Prompting & DP-Reflection & 82.330000 & NaN & 1.000000 & False \\
qwen2-math:1.5b & Direktes Prompting & ReAct & 82.330000 & NaN & 1.000000 & False \\
qwen2-math:1.5b & Direktes Prompting & ReWOO & 82.330000 & 0.330000 & 0.000000 & True \\
qwen2-math:1.5b & DP-Reflection & ReAct & NaN & NaN & 1.000000 & False \\
qwen2-math:1.5b & DP-Reflection & ReWOO & NaN & 0.330000 & 1.000000 & False \\
qwen2-math:1.5b & ReAct & ReWOO & NaN & 0.330000 & 1.000000 & False \\
qwen2.5:0.5b & Direktes Prompting & DP-Reflection & 40.330000 & 35.000000 & 0.177253 & False \\
qwen2.5:0.5b & Direktes Prompting & ReAct & 40.330000 & 15.670000 & 0.000000 & True \\
qwen2.5:0.5b & Direktes Prompting & ReWOO & 40.330000 & 12.330000 & 0.000000 & True \\
qwen2.5:0.5b & DP-Reflection & ReAct & 35.000000 & 15.670000 & 0.000000 & True \\
qwen2.5:0.5b & DP-Reflection & ReWOO & 35.000000 & 12.330000 & 0.000000 & True \\
qwen2.5:0.5b & ReAct & ReWOO & 15.670000 & 12.330000 & 0.237892 & False \\
qwen3:0.6b & Direktes Prompting & DP-Reflection & 61.000000 & 68.670000 & 0.048413 & True \\
qwen3:0.6b & Direktes Prompting & ReAct & 61.000000 & 64.670000 & 0.351956 & False \\
qwen3:0.6b & Direktes Prompting & ReWOO & 61.000000 & 55.330000 & 0.158514 & False \\
qwen3:0.6b & DP-Reflection & ReAct & 68.670000 & 64.670000 & 0.298250 & False \\
qwen3:0.6b & DP-Reflection & ReWOO & 68.670000 & 55.330000 & 0.000678 & True \\
qwen3:0.6b & ReAct & ReWOO & 64.670000 & 55.330000 & 0.018992 & True \\
qwen3:1.7b & Direktes Prompting & DP-Reflection & 66.670000 & 87.330000 & 0.000000 & True \\
qwen3:1.7b & Direktes Prompting & ReAct & 66.670000 & 85.330000 & 0.000000 & True \\
qwen3:1.7b & Direktes Prompting & ReWOO & 66.670000 & 74.330000 & 0.038974 & True \\
qwen3:1.7b & DP-Reflection & ReAct & 87.330000 & 85.330000 & 0.475637 & False \\
qwen3:1.7b & DP-Reflection & ReWOO & 87.330000 & 74.330000 & 0.000041 & True \\
qwen3:1.7b & ReAct & ReWOO & 85.330000 & 74.330000 & 0.000701 & True \\
smollm2:360m & Direktes Prompting & DP-Reflection & 5.330000 & NaN & 1.000000 & False \\
smollm2:360m & Direktes Prompting & ReAct & 5.330000 & NaN & 1.000000 & False \\
smollm2:360m & Direktes Prompting & ReWOO & 5.330000 & 2.330000 & 0.054815 & False \\
smollm2:360m & DP-Reflection & ReAct & NaN & NaN & 1.000000 & False \\
smollm2:360m & DP-Reflection & ReWOO & NaN & 2.330000 & 1.000000 & False \\
smollm2:360m & ReAct & ReWOO & NaN & 2.330000 & 1.000000 & False \\
\bottomrule
\end{tabular}